# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20181023_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
